---
- name: Install haproxy
  hosts: localhost

  tasks:
  - name: Install make
    apt:
      name: make
      state: present
  - name: Install gcc
    apt:
      name: gcc
      state: present
  - name: Make haproxy folder
    file:
      path: /home/ubuntu/haproxy
      state: directory
  - name: Download haproxy binary
    get_url:
      url: http://www.haproxy.org/download/1.6/src/haproxy-1.6.9.tar.gz
      dest: /home/ubuntu/haproxy
  - name: Unzip haproxy binary
    unarchive:
      src: /home/ubuntu/haproxy/haproxy-1.6.9.tar.gz
      dest: /home/ubuntu/haproxy
  - name: Make haproxy
    make:
      chdir: /home/ubuntu/haproxy
  - name: Install haproxy
    make:
      chdir: /home/ubuntu/haproxy
      target: install
