---
- name: Install node/npm
  hosts: localhost

  tasks:
  - name: Install node
    apt:
      name: nodejs
      state: present
  - name: Install npm
    apt:
      name: npm
      state: present
  - name: Install npm dependencies
    npm:
      path: /home/ubuntu/web_server
  - name: Link nodejs as node
    shell: ln -s /usr/bin/nodejs /usr/bin/node
