---
- name: Install reactjs
  hosts: localhost

  tasks:
  - name: Make base folder
    file:
      path: /home/ubuntu/web_server
      state: directory
  - name: Install react
    npm:
      name: react
      global: yes
      state: present
      path: /home/ubuntu/web_server
  - name: Install react-dom
    npm:
      name: react-dom
      global: yes
      state: present
      path: /home/ubuntu/web_server
  - name: Install express
    npm:
      name: express
      global: yes
      state: present
      path: /home/ubuntu/web_server
  - name: Move webserver code
    copy:
      src: /tmp/hello_world.js
      dest: /home/ubuntu/web_server/routes/hello_world.js
  - name: Copy HTML
    copy:
      src: /tmp/hello.html
      dest: /home/ubuntu/web_server/views/hello.html
