---
- name: Install serf
  hosts: localhost

  tasks:
  - name: Make serf folder
    file:
      path: /home/ubuntu/serf
      state: directory
  - name: Download serf binary
    get_url:
      url: https://releases.hashicorp.com/serf/0.8.0/serf_0.8.0_linux_amd64.zip
      dest: /home/ubuntu/serf
  - name: Unzip serf binary
    unarchive:
      src: /home/ubuntu/serf/serf_0.8.0_linux_amd64.zip
      dest: /home/ubuntu/serf
  - name: Link serf binary
    shell: mv /home/ubuntu/serf/serf /usr/bin
