---
- name: Copy sourcecode
  hosts: localhost

  tasks:
  - name: Make base folder
    file:
      path: /home/ubuntu/web_server
      state: directory
  - name: Move package.json
    copy:
      src: /tmp/package.json
      dest: /home/ubuntu/web_server/
  - name: Make routes folder
    file:
      path: /home/ubuntu/web_server/routes
      state: directory
  - name: Move webserver code
    copy:
      src: /tmp/hello_world.js
      dest: /home/ubuntu/web_server/routes/hello_world.js
  - name: Make views folder
    file:
      path: /home/ubuntu/web_server/views
      state: directory
  - name: Copy HTML
    copy:
      src: /tmp/hello.njk
      dest: /home/ubuntu/web_server/views/hello.njk
  - name: Move webserver code
    copy:
      src: /tmp/express_server.js
      dest: /home/ubuntu/web_server/app.js
